### ISSUE TITLE
Audio module can not be unloaded even when not in use

### ISSUE THREAD

**Issue by azizulhakim** [azizulhakim/beagleusb#3]
**_rmmod**_ command can't unload the audio module if the device is connected in USB cable. Requires detachment of USB cable before unloading.

> sudo rmmod beagle 
> rmmod: ERROR: Module beagle is in use

**Comment by pkpio** [comment]
Does any other module uses functions exported by this module?

**Comment by azizulhakim** [comment]
@praveendath92 No. Seems like ALSA is holding the module if there is some device connected for that module.

**Comment by pkpio** [comment]
Check if any of the methods in the module are sleeping, may be in a different thread or callback

**Comment by azizulhakim** [comment]
If the device is connected to the USB, **_pulseaudio**_ mixer interface will hold the device. So we can't use the **_rmmod**_ command to unload the driver. To unload we have to forcefully stop **_pulseaudio**_ which has other inappropriate impact. So the normal operation should be to disconnect the device first and then unload the module. Closing the issue.
